# flutter build web --wasm --no-tree-shake-icons

name: spnk
description: Sivaprasad NK's portfolio

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  # animated_text_kit: ^4.2.1
  # animations: ^2.0.1
  auto_animated: ^3.0.0
  auto_size_text: ^3.0.0
  avatar_glow: ^2.0.2
  # blobs: ^2.0.0
  blur: ^3.1.0
  # bordered_text: ^2.0.0
  # carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  # dio: ^4.0.0
  # faded_widget: ^2.0.0
  # flip_card: ^0.6.0
  flutter:
    sdk: flutter
  # flutter_animated_dialog: ^2.0.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.2.0
  # gradients: ^0.1.1+1
  # hovering: ^1.0.4
  # http: ^0.13.3
  # infinite_carousel: ^1.0.2
  lint: ^1.8.2
  lottie: ^1.0.1
  # mouse_parallax: ^1.1.0
  # page_view_indicators: ^2.0.0
  # provider: ^5.0.0
  # qr_flutter: ^4.0.0
  # shared_preferences: ^2.0.13
  riverpod: ^2.5.1
  tab_indicator_styler: ^2.0.0
  # transition: ^2.0.2
  universal_html: ^2.0.8
  url_launcher: ^6.0.6
  # wave: ^0.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_app_name:
  name: "Sivaprasad NK"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/dash/
    - assets/svg/
    - assets/lotties/
    - assets/images/quizApp/
    - assets/images/quotesApp/
    - assets/images/social-media/
    - assets/images/website/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PatuaOne
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Italic-VariableFont_wght.ttf
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
    - family: Zina
      fonts:
        - asset: assets/fonts/Zina-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
